<?php

use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_form_alter().
 */
function login_redirect_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  if ($form_id === 'user_login_form') {
    $form['#submit'][] = 'login_redirect_user_login_form_submit';
  }
}

/**
 * Custom submit handler for the user login form.
 */
function login_redirect_user_login_form_submit($form, FormStateInterface $form_state) {
  $form_state->setRedirect('<front>');
}
