<?php

declare(strict_types=1);

/**
 * @file
 * Functions to support theming in the lcyc_radix theme.
 */

/**
 * Implements hook_preprocess_HOOK() for html.html.twig.
 */
function lcyc_radix_preprocess_html(array &$variables): void {

}

/**
 * Implements hook_preprocess_HOOK() for page.html.twig.
 */
function lcyc_radix_preprocess_page(array &$variables): void {

}

/**
 * Implements hook_preprocess_HOOK() for node.html.twig.
 */
function lcyc_radix_preprocess_node(array &$variables): void {
  // Hide submitted by / author + date on specific content types
  if ($variables['node']->getType() == 'story' || $variables['node']->getType() == 'article') {
    $variables['display_submitted'] = FALSE;
  } 
}
